import { defineStore } from 'pinia';

export const useSightStore = defineStore('sights', {
  state: () => {
    return {
      sightsTab: [
          {
            index: 0,
            imageUrl: '/Rectangle 42.png',
            title: 'Casa Bastillo',
            description: 'Casa Batlló is a building with apartments designed by Antoni Gaudí, completely in the style of Catalan Modernism. The shapes of the house are based on the legend of George and the dragon. You will be amazed at the many beautiful details, colors and mosaics.',
            redirectUrl: 'https://www.casabatllo.es/',
            isLiked: false,
          },
          {
            index: 1,
            imageUrl: '/Rectangle 44.png',
            title: 'Casa Mila-La perdrera',
            description: 'Another beautiful building and a striking example of modernist architecture designed by Antoni Gaudí is Casa Milà, also known as La Pedrera. Translated, this means the quarry, named after the rugged appearance of the complex.',
            redirectUrl: 'https://www.casabatllo.es/antoni-gaudi/casa-mila-la-pedrera/',
            isLiked: false,
          },
          {
            index: 2,
            imageUrl: '/Rectangle 46.png',
            title: 'Casa Vicens',
            description: 'In the Gràcia district, behind a wrought-iron gate in the shape of palm leaves, lies the best kept secret: the striking and colorful building of Casa Vicens. This building was the first major design by Antoni Gaudi in Barcelona and part of the UNESCO World Heritage List. After completing this building, Gaudí won the elite of Barcelona with his distinctive style/.',
            redirectUrl: 'https://casavicens.org/',
            isLiked: false,
          },
          {
            index: 3,
            imageUrl: '/Rectangle 48.png',
            title: 'Cathredal',
            description: 'The cathedral in Barcelona`s Gothic Quarter was named for the patron saint of Barcelona, Saint Eulalia; the official Catalan name - Catedral de la Santa Creu i Santa Eulalia - means Cathedral of the Holy Cross and Saint Eulalia. The commonly used name La Seu cathedral refers to the status of the church as the seat of the diocese. After the Sagrada Familia, this is the most important church of Barcelona.',
            redirectUrl: 'https://catedralbcn.org/en/',
            isLiked: false,
          },
          {
            index: 4,
            imageUrl: '/Rectangle 50.png',
            title: 'La Sagrada Familia',
            description: 'The absolute number 1 attraction in Barcelona Spain is the Sagrada Familia; the holy cathedral designed by Antoni Gaudí. The unfinished church will probably be completed in 2026 and has to be part of your city break. You can even ascend the towers for an amazing view.',
            redirectUrl: 'https://sagradafamilia.org/en/home',
            isLiked: false,
          },
          {
            index: 5,
              imageUrl: '/Rectangle 52.png',
              title: 'Sant Pau Hospital',
              description: 'The Hospital de la Santa Creu i de Sant Pau is the former hospital of Barcelona and was beautifully designed by the architect Lluís Domènech i Montane and is one of the prime examples of Catalan modernist architecture.',
              redirectUrl: 'https://www.santpau.cat/en/web/public/home',
              isLiked: false,
          },
          {
            index: 6,
            imageUrl: '/Rectangle 54.png',
            title: 'Palau Guëll',
            description: 'The Palau Güell of Antoni Gaudí was built between 1886 and 1890 and is located near the famous Ramblas. The Palau Güell is a dark and modernist palace built for the wealthy industrialist and shipping magnate Eusebi Güell; he was a lover of the works of Gaudi and also financed several of Gaudi`s projects.',
            redirectUrl: 'https://inici.palauguell.cat/en/',
            isLiked: false,
        },
        {
            index: 7,
            imageUrl: '/Rectangle 56.png',
            title: 'Columbus Monument',
            description: 'Centrally located in the Plaça de la Porte de Pau in Barcelona`s harbour and at the start of the Ramblas is a large cast-iron column supporting a statue of Christopher Columbus. The Columbus monument (60 metres high), known in Catalan as the Monument a Colom, was designed for the 1888 World Fair that was held in Barcelona.',
            redirectUrl: 'https://inici.palauguell.cat/en/',
            isLiked: false,
        },
        {
            index: 8,
            imageUrl: '/Rectangle 58.png',
            title: 'Arc de Triomf',
            description: 'At the time, the triumphal arch "Arc de Triomf" served as the main entrance to the 1888 World Fair that was held in the Parc de la Ciutadella of Barcelona. The triumphal arch made of red brick is not actually in the park, but nearby, precisely the link between the Passeig de Lluís Companys and the Passeig de Sant Joan, at Metro Station Arc de Triomf. The height of the triumphal arch is 30 metres, and it was designed by the Spanish architect Josep Vilaseca i Casanovas. The arch has grown into one of the iconic sights of Barcelona.',
            redirectUrl: 'https://www.barcelona.de/en/barcelona-arc-de-triomf.html',
            isLiked: false,
        },
        {
            index: 9,
            imageUrl: '/Rectangle 60.png',
            title: 'Santa Maria del Mar',
            description: 'The Santa María del Mar basilica of Barcelona, located in the district La Ribera, is a church that was built between 1329 and 1383, during the heyday of Catalonia as a trading and sea-faring nation. It`s also called the cathedral of La Ribera. The church is an excellent example of Catalan gothic, with a purity and unity of style that was very rare in the Middle Ages.',
            redirectUrl: 'http://www.santamariadelmarbarcelona.org/',
            isLiked: false,
        },
        {
            index: 10,
            imageUrl: '/Rectangle 43.png',
            title: 'Pedralbes Monastery',
            description: 'The monastery of Pedralbes (Reial Monestir de Santa Maria de Pedralbes) is a Gothic monastery in Barcelona. Today it is a museum that is accessible to the public. The museum offers insight into monastic life during the middle ages. The monastery is located on the north-west edge of the city (near Finca Güell) and does not get many tourists. If you`re in Barcelona for an extended stay, it`s certainly worth to visit this surprising attraction and sea of tranquillity.',
            redirectUrl: 'https://www.monestirpedralbes.barcelona/en/monastery',
            isLiked: false,
        },
        {
            index: 11,
            imageUrl: '/Rectangle 64.png',
            title: 'Casa de les Punxes',
            description: 'Also known as La Casa Terradas,Casa de les Punxes was built by the architect Josep Puig i Cadafalch in 1905, under the commission of Ángela Brutau for his three daughters, Ángela, Rosa and Josefa. ',
            redirectUrl: 'https://www.barcelona.cat/en/discoverbcn/pics/la-casa-de-les-punxes-92086008882/',
            isLiked: false,
        },
      ],
      museumsTab: [
        {
          index: 12,
          imageUrl: '/Rectangle 42.png',
          title: 'Picasso Museum',
          description: 'Barcelona`s Picasso Museum is dedicated to one of Spain`s greatest artists, in the city where Pablo Picasso spent the first period of his young adult life and where he exhibited his first works of art. The museum is located in the Born district.',
          redirectUrl: 'https://museupicassobcn.cat/en',
          isLiked: false,
        },
        {
          index: 13,
          imageUrl: '/Rectangle 52.png',
          title: 'Museu Nacional d’ART de Catalunya',
          description: 'The National Art Museum of Catalonia (in Catalan: Museu Nacional d`Art de Catalunya), also known by its acronym MNAC, is located in the city of Barcelona (Spain). It is particularly renowned for its collection of Romanesque art, which is considered to be one of the most comprehensive in the world. Its director is Josep Serra i Villalba.',
          redirectUrl: 'https://www.museunacional.cat/en',
          isLiked: false,
        },
        {
          index: 14,
          imageUrl: '/Rectangle56.png',
          title: 'Museu Europeu d’Art Modern',
          description: 'the Museu Europeu d’Art Modern (MEAM) is a museum dedicated to modern and contemporary art. The museum is situated in a beautiful 19th-century palace, offering an intimate and peaceful atmosphere for visitors to appreciate the art.',
          redirectUrl: 'https://www.meam.es/en/exhibitions/',
          isLiked: false,
        },
        {
          index: 15,
          imageUrl: '/Rectangle 299.png',
          title: 'Museu d’Historia',
          description: 'The Barcelona History Museum is a museum that preserves, studies, exhibits and transmits the historical heritage of the city of Barcelona, from its origins to the present day. Its headquarters are located on the Plaça del Rei in the centre of the old town (Ciutat Vella), in the Gothic quarter (Barri Gotic). It is one of several heritage sites scattered around the city. Most of them are archaeological sites containing remains of the ancient Roman city, known in Latin as Barcino.',
          redirectUrl: 'https://www.mhcat.cat/',
          isLiked: false,
        },
        {
          index: 16,
          imageUrl: '/Rectangle44.png',
          title: 'Museum FC Barcelona Camp Nou',
          description: 'The FCBarcelona President Nuñez Museum is the museum of FC Barcelona. It is located in the Camp Nou and was inaugurated on 24 September 1984 under the presidency of Josep Lluís Núñez. Covering an area of 3,550 m² on two floors, the museum traces the history of the Catalan club since its foundation in 1899.',
          redirectUrl: 'https://www.fcbarcelona.com/en/tickets/camp-nou-experience',
          isLiked: false,
        },
        {
          index: 17,
          imageUrl: '/Rectangle 62.png',
          title: 'Moco Museum',
          description: 'The Moco Museum in Barcelona is a museum located in the city of Barcelona, Spain. It is located at 25, rue de Montcada, in the El Born district. The museum offers temporary and permanent exhibitions of contemporary art and popular culture. It is open every day except Sunday, and tickets can be booked online to avoid queues.',
          redirectUrl: 'https://mocomuseum.com/locations/barcelona',
          isLiked: false,
        },
      ],
      parksTab: [
        {
          index: 18,
          imageUrl: '/1 (1).png',
          title: 'Park de la Ciutadella',
          description: 'The Moco Museum in Barcelona is a museum located in the city of Barcelona, Spain. It is located at 25, rue de Montcada, in the El Born district. The museum offers temporary and permanent exhibitions of contemporary art and popular culture. It is open every day except Sunday, and tickets can be booked online to avoid queues.',
          redirectUrl: 'https://www.introducingbarcelona.com/parc-de-la-ciutadella',
          isLiked: false,
        },
        {
          index: 19,
          imageUrl: '/1 (7).png',
          title: 'Parc del Laberint d’Horta',
          description: 'The Moco Museum in Barcelona is a museum located in the city of Barcelona, Spain. It is located at 25, rue de Montcada, in the El Born district. The museum offers temporary and permanent exhibitions of contemporary art and popular culture. It is open every day except Sunday, and tickets can be booked online to avoid queues.',
          redirectUrl: 'https://patrimoni.gencat.cat/en/collection/labyrinth-horta-park',
          isLiked: false,
        },
        {
          index: 20,
          imageUrl: '/1 (6).png',
          title: 'Parc Guëll',
          description: 'The Moco Museum in Barcelona is a museum located in the city of Barcelona, Spain. It is located at 25, rue de Montcada, in the El Born district. The museum offers temporary and permanent exhibitions of contemporary art and popular culture. It is open every day except Sunday, and tickets can be booked online to avoid queues.',
          redirectUrl: 'https://parkguell.barcelona/en',
          isLiked: false,
        },
        {
          index: 21,
          imageUrl: '/1 (5).png',
          title: 'Parc de Montjuïc',
          description: 'The Moco Museum in Barcelona is a museum located in the city of Barcelona, Spain. It is located at 25, rue de Montcada, in the El Born district. The museum offers temporary and permanent exhibitions of contemporary art and popular culture. It is open every day except Sunday, and tickets can be booked online to avoid queues.',
          redirectUrl: 'https://www.castillomontjuic.com/',
          isLiked: false,
        },
        {
          index: 22,
          imageUrl: '/1 (4).png',
          title: 'Jardi Botanic de Barcelona',
          description: 'The Moco Museum in Barcelona is a museum located in the city of Barcelona, Spain. It is located at 25, rue de Montcada, in the El Born district. The museum offers temporary and permanent exhibitions of contemporary art and popular culture. It is open every day except Sunday, and tickets can be booked online to avoid queues.',
          redirectUrl: 'https://museuciencies.cat/en/the-nat/venues/botanical-garden-of-barcelona/',
          isLiked: false,
        },
        {
          index: 23,
          imageUrl: '/1 (3).png',
          title: 'Parc de Miro',
          description: 'The Moco Museum in Barcelona is a museum located in the city of Barcelona, Spain. It is located at 25, rue de Montcada, in the El Born district. The museum offers temporary and permanent exhibitions of contemporary art and popular culture. It is open every day except Sunday, and tickets can be booked online to avoid queues.',
          redirectUrl: 'https://www.barcelona.cat/en/que-pots-fer-a-bcn/parcs-i-jardins/parc-de-joan-miro-92086012013',
          isLiked: false,
        },
      ],
      restaurantsTab: [
        {
          index: 18,
          imageUrl: '/tagliatella.jpg',
          title: 'La Tagliatella',
          description: 'La Tagliatella stands at the foot of the hill of Montjüic, on the top floor of Barcelona’s Las Arenas Mall, a building designed by the British architect Richard Rogers in collaboration with Alonso Balaguer Arquitecto Asociados.',
          redirectUrl: 'https://www.latagliatella.es/restaurantes/barcelona/cc-las-arenas-barcelona',
          isLiked: false,
        },
        {
          index: 19,
          imageUrl: '/elsalon.png',
          title: 'El Salón',
          description: 'The Salón Restaurant opened in 1995 as the first bistro restaurant in Barcelona. Located in the iconic and energetic Gothic Quarter of the city, it has been characterised by a cuisine based on high quality local, and seasonal products with a wide variety of Mediterranean flavours and scents.It’s homemade, healthy style creates a great experience for the most demanding locals and visitors from around the world. Since its inception, the Salón maintains a casual and bohemian feel with recycled furniture and everyday objects that give a warm and informal feeling of home, transmitting its characteristic personal style. The outdoor terrace, located in the Plaça Traginers next to the Roman city wall and its views, make the culinary experience intimate and unforgettable.',
          redirectUrl: 'http://www.elsalonrestaurant.com/',
          isLiked: false,
        },
        {
          index: 20,
          imageUrl: '/elricon.png',
          title: 'El Rincón',
          description: 'It is located a few meters from the famous market of La Boquería and the Ramblas of Barcelona, with more than 40 years of history you will find a place with a comfortable and cozy atmosphere where you will be surprise by our varied and modern cuisine with unique flavors.',
          redirectUrl: 'https://www.elrinconbarcelona.com/en/inicio-english/',
          isLiked: false,
        },
        {
          index: 21,
          imageUrl: '/antic.png',
          title: 'Antic Bocoi del Gotic',
          description: 'The Antic Bocoi del Gotic occupies a historic building dating back to the 18th century, which gives it a special charm. Its traditional and careful decoration will transport you to another era, allowing you to enjoy an authentic and cozy experience.',
          redirectUrl: 'https://www.barcelona.zone/restaurant-antic-bocoi-gotic',
          isLiked: false,
        },
        {
          index: 22,
          imageUrl: '/ladesa.png',
          title: 'La Desayunería',
          description: 'At La Desayunería you can find authentic American Breakfast style breakfasts, served all day long. La Desayunería was born from a trip to the United States where the only thing we wanted to eat were breakfast dishes. Eggs, milkshakes, pancakes, bacon, omelettes, grilled cheese, all these dishes were our source of nourishment during our trip across North America.',
          redirectUrl: 'https://www.instagram.com/massa_pasta.bcn/',
          isLiked: false,
        },
        {
          index: 23,
          imageUrl: '/viana.png',
          title: 'Viana Barcelona',
          description: 'A gastronomic oasis, in two beautiful locations, just a few meters from Plaza Real',
          redirectUrl: 'https://www.vianabcn.com/en/',
          isLiked: false,
        },
      ]
    }
  },
  persist: true,
});